name: CI Server (Python with Coverage)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # importante para SonarCloud

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and testing tools
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pytest pytest-cov

      - name: Check syntax
        run: |
          find . -type f -name "*.py" -exec python -m py_compile {} +

      - name: Run unit tests with coverage (XML + terminal)
        run: |
          python -m pytest --cov=. \
                           --cov-report=xml:coverage.xml \
                           --cov-report=term-missing -v

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=emiliozallocco1
            -Dsonar.projectKey=EmilioZallocco1_ahorcado_Agiles
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
